server:
  port: 8081
spring:  application:    name: imageProcessingService
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka